import argparse
import sys
from pathlib import Path
import yaml

# Adjust path to import from the project
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from mlx_rl_trainer.core.config import (
    DataConfig,
    ExperimentConfig,
    ModelConfig,
    TrainerParams,
    GenerationConfig,
    RewardConfig,
    EvaluatorConfig,
    CheckpointConfig,
    MonitoringConfig,
)


def get_default_config() -> ExperimentConfig:
    """Creates a default experiment configuration object with examples."""
    trainer = TrainerParams(
        output_dir=Path("./outputs/default_run"),
        validate_every=100,
        eval_every=200,
    )
    model = ModelConfig(model_path=Path("path/to/your/base_model"), use_lora=True)
    data = DataConfig(
        train_path=Path("path/to/your/train_data.jsonl"),
        val_path=Path("path/to/your/val_data.jsonl"),
        data_validation_script_path=None,  # Optional: Path("path/to/your/validator.py")
    )
    rewards = [
        RewardConfig(name="format_structure", weight=0.1, config={}),
        RewardConfig(
            name="verify_response",
            weight=0.9,
            config={
                "key_name": "verifiable_answer_str",
                "verification_mode": "str_normalized_match",
                "similarity_weight": 0.3,
                "verification_weight": 0.7,
            },
        ),
    ]
    evaluation = [
        EvaluatorConfig(
            name="gsm8k",
            dataset_path="gsm8k",
            dataset_subset="main",
            split="test",
            config={"num_samples": 50},
        )
    ]
    checkpointing = CheckpointConfig(best_model_metric="validation/reward_mean")

    return ExperimentConfig(
        trainer=trainer,
        model=model,
        data=data,
        rewards=rewards,
        evaluation=evaluation,
        checkpointing=checkpointing,
        monitoring=MonitoringConfig(),
        generation=GenerationConfig(),
    )


def dump_config_to_yaml(config: ExperimentConfig, output_path: Path):
    """Dumps the Pydantic model to a YAML file."""
    config_dict = config.model_dump(mode="json")

    # Custom dumper to handle Path objects correctly
    class PathDumper(yaml.SafeDumper):
        def represent_data(self, data):
            if isinstance(data, Path):
                return self.represent_str(str(data))
            return super().represent_data(data)

    yaml_str = yaml.dump(config_dict, Dumper=PathDumper, sort_keys=False, indent=2)
    commented_yaml_str = (
        "# MLX Reinforcement Learning Trainer Configuration\n"
        "# Generated by dump_config.py\n\n" + yaml_str
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(commented_yaml_str)

    print(f"Default configuration written to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Dump the default config for the MLX RL Trainer."
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default="default_config.yml",
        help="Output YAML file path.",
    )
    args = parser.parse_args()
    dump_config_to_yaml(get_default_config(), Path(args.output))


if __name__ == "__main__":
    main()
