"""
A reward function that verifies the generated response against a ground truth answer.
"""
import logging
from typing import Any, Dict, Optional

from mlx_rl_trainer.rewards.base_reward import BaseReward
from mlx_rl_trainer.rewards.registry import register_reward
from mlx_rl_trainer.rewards.context import RewardContext
from mlx_rl_trainer.utils.text_utils import _jaccard_similarity as jaccard_similarity, _normalize_ans_for_match as normalize_text

logger = logging.getLogger(__name__)

@register_reward("verify_response")
class VerifyResponseReward(BaseReward):
    """
    A reward function that verifies if the generated response matches a verified answer string.
    It supports multiple verification modes and can blend a verification score with a similarity score.
    """

    def __init__(
        self,
        similarity_weight: float = 0.5,
        verification_weight: float = 0.5,
        verification_mode: str = "str_normalized_match",
    ):
        """
        Initializes the VerifyResponseReward.

        Args:
            similarity_weight (float): The weight for the similarity score (e.g., Jaccard).
            verification_weight (float): The weight for the verification score.
            verification_mode (str): The mode for verification. Supported modes:
                - "str_exact_match": Exact string match.
                - "str_normalized_match": Normalized string match (lowercase, no punctuation).
                - "math_eval_match": Evaluates the mathematical expressions and compares results.
                - "python_script_output_based": Executes a Python script and compares output.
        """
        if verification_mode not in [
            "str_exact_match",
            "str_normalized_match",
            "math_eval_match",
            "python_script_output_based",
        ]:
            raise ValueError(f"Unsupported verification_mode: {verification_mode}")

        self.similarity_weight = similarity_weight
        self.verification_weight = verification_weight
        self.verification_mode = verification_mode

    def compute(
        self, generated_text: str, context: RewardContext
    ) -> float:
        """
        Computes the reward for a single generated text.

        Args:
            generated_text (str): The text generated by the model.
            context (RewardContext): The context containing metadata and other information.

        Returns:
            float: The computed reward, ranging from 0.0 to 1.0.
        """
        verified_answer = context.metadata.get("verified_answer_str")
        if not verified_answer:
            return 0.0

        # 1. Calculate verification score
        verification_score = self._verify(generated_text, verified_answer)

        # 2. Calculate similarity score
        similarity_score = jaccard_similarity(generated_text, verified_answer)

        # 3. Blend scores
        final_reward = (
            self.similarity_weight * similarity_score
            + self.verification_weight * verification_score
        )
        return float(final_reward)

    def _verify(self, generated: str, truth: str) -> float:
        """Helper function to perform verification based on the selected mode."""
        if self.verification_mode == "str_exact_match":
            return 1.0 if generated.strip() == truth.strip() else 0.0

        if self.verification_mode == "str_normalized_match":
            return 1.0 if normalize_text(generated) == normalize_text(truth) else 0.0

        if self.verification_mode == "math_eval_match":
            try:
                return 1.0 if eval(generated) == eval(truth) else 0.0
            except:
                return 0.0

        if self.verification_mode == "python_script_output_based":
            # This is a placeholder for a more complex implementation
            # that would involve sandboxed code execution.
            logger.warning("`python_script_output_based` is not fully implemented and will default to normalized string match.")
            return 1.0 if normalize_text(generated) == normalize_text(truth) else 0.0

        return 0.0
