"""Utility module Initialization."""

from .mlx_utils import (
    _is_metal_internal_error,
    metal_recover,
    metal_safe_apply_gradients,
    _create_4d_attention_mask,
    safe_make_sampler,
    make_dynamic_tag_bias_processor,
    _first_token_ids_for_lexemes,
    _letter_token_ids,
    _resolve_tag_ids,
    scale_grads_by_band,
    mask_grads_to_layer_band,
    mask_grads_to_specific_layers,
    ContentAlignBridge,
    _mask_after_answer,
    _find_embedding_layer,
    _freeze_module,
    metal_before_update,
    _global_grad_norm,
    _maybe_clip_grad_norm,
    limit_memory,
)

from .text_utils import (
    _preview,
    _strip_markup,
    _count_words,
    _tokenize_set,
    _normalize_ans_for_match,
    _contains_keywords,
    _contains_phrase,
    _has_non_ascii,
    _extract_action_phrases,
    _extract_python_code,
    extract_think_region,
    extract_answer_region,
    _extract_think_answer_lengths,
    _extract_final_numeric,
    _indices_to_letters,
    _letters_to_canonical,
    _match_ref_to_option_index,
    _extract_mcq_options,
    _infer_mcq_ref_letters,
    _mcq_meta_from_sample,
    apply_chat_template_wrapper,
    _tfidf_cosine,
    _jaccard_similarity,
    _looks_garbage,
    _ascii_ratio,
)
from .mcq_utils import _extract_predicted_letters
from .math_utils import safe_divide, safe_mean, safe_std, softmax, log_softmax
from .distributed import DistributedUtil

__all__ = [
    # mlx_utils
    "metal_safe_apply_gradients",
    "limit_memory",
    "_is_metal_internal_error",
    "metal_recover",
    "_create_4d_attention_mask",
    "safe_make_sampler",
    "make_dynamic_tag_bias_processor",
    "_first_token_ids_for_lexemes",
    "_letter_token_ids",
    "_resolve_tag_ids",
    "scale_grads_by_band",
    "mask_grads_to_layer_band",
    "mask_grads_to_specific_layers",
    "ContentAlignBridge",
    "_mask_after_answer",
    "_find_embedding_layer",
    "_freeze_module",
    "metal_before_update",
    "_global_grad_norm",
    "_maybe_clip_grad_norm",
    # text_utils
    "_preview",
    "_strip_markup",
    "_count_words",
    "_tokenize_set",
    "_normalize_ans_for_match",
    "_contains_keywords",
    "_contains_phrase",
    "_has_non_ascii",
    "_extract_action_phrases",
    "_extract_python_code",
    "extract_think_region",
    "extract_answer_region",
    "_extract_think_answer_lengths",
    "_extract_final_numeric",
    "_indices_to_letters",
    "_letters_to_canonical",
    "_match_ref_to_option_index",
    "_extract_mcq_options",
    "_infer_mcq_ref_letters",
    "_mcq_meta_from_sample",
    "apply_chat_template_wrapper",
    "_tfidf_cosine",
    "_jaccard_similarity",
    "_looks_garbage",
    "_ascii_ratio",
    # mcq_utils
    "_extract_predicted_letters",
    # math_utils
    "safe_divide",
    "safe_mean",
    "safe_std",
    "softmax",
    "log_softmax",
    # distributed
    "DistributedUtil",
]
